### ISSUE TITLE
Video#filesize does not work after setting config.format

### ISSUE THREAD

**Issue by PoVa** [layer8x/youtube-dl.rb#35]
```ruby
video = YoutubeDL::Video.new('https://www.youtube.com/watch?v=XXXXXXXXXX')
video.options.configure do |c|
  c.extract_audio = true
  c.audio_format = 'mp3'
  c.format = :worst
end

puts video.filesize
```

```
/home/kristupas/.rvm/gems/ruby-2.2.4/gems/youtube-dl.rb-0.3.0.2016.05.01/lib/youtube-dl/video.rb:68:in `method_missing': undefined method `filesize' for #<YoutubeDL::Video:0x0000000272a040> (NoMethodError)
	from test.rb:10:in `<main>'
```

**Comment by sapslaj** [comment]
There's not really an easy way to get the filesize since not every format supplies that information. It's also rather difficult to get the requested format information, which I'll to the list of things to improve on. The easiest way I've found is to do `video.formats.select { |format| format['format_id'] == video.format_id }.first` then use the keys from that. 

But as I mentioned, not every format provides filesize so running your example returns `nil`
 
`[11] pry(main)> video.formats.select { |format| format['format_id'] == video.format_id }.first['filesize']
=> nil
`

But if I set the format to 249, a format which I know provides a filesize, I'll get something in return.
`[1] pry(main)> video.formats.select { |format| format['format_id'] == video.format_id }.first['filesize']
=> 55351
` 

I'll try to make the API a lot cleaner in the next 0.3.1 version. Thanks for reporting this though!

**Comment by mm580486** [comment]
how fix this issue , i want know video filesize 
`[11] pry(main)> video.formats.select { |format| format['format_id'] == video.format_id }.first['filesize'] => nil`
@sapslaj
